spring:
  datasource:
    url: jdbc:mysql://localhost:3306/address_book #change "address_book" with you own database
    username: root #if you haven't configured username and password for your database leave empty
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    sendgrid:
      api-key: ${SENDGRID_API_KEY} #for production this should be stored in env variables


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

