spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adress_book #change "company" with you own database
    username: root #if you haven't configured username and password for your database leave empty
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    sendgrid:
      api-key: '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' #for production this should be stored in env variables


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

