spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company #change "company" with you own database
    username: root #if you haven't configured username and password for your database leave empty
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

    #This is a .yml file though we can refactor it to .properties and copy and paste the corresponding dialect for that extension
